# Generated by Django 5.0.1 on 2024-02-14 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_test_end_date_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 13, 0, 51, 147339, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
